INSERT INTO series (title, author_id, subgenre_id) VALUES ("Red Rising", 1, 2);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("Inheritance", 2, 1);
INSERT INTO books (title, year, series_id) VALUES ("Eragon", 2003, 2);
INSERT INTO books (title, year, series_id) VALUES ("Eldest", 2005, 2);
INSERT INTO books (title, year, series_id) VALUES ("Inheritance", 2011, 2);
INSERT INTO books (title, year, series_id) VALUES ("Red Rising", 2014, 1);
INSERT INTO books (title, year, series_id) VALUES ("Golden Son", 2015, 1);
INSERT INTO books (title, year, series_id) VALUES ("Morning Star", 2016, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Darrow", "Red", "Reap what you sow", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Mustang", "Gold", "Girls run the world", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Cassius", "Gold", "Iron Gold", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Sevro", "Gold/Red", "The meanest one wins", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Eragon", "Human", "Cry", 2, 2);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Aria", "Elf", "Do your duty", 2, 2);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Saphira", "Dragon", "Pay attention to me", 2, 2);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("Murtaugh", "Human", "Screw you lil bro", 2, 2);
INSERT INTO authors (name) VALUES ("Pierce Brown");
INSERT INTO authors (name) VALUES ("Christopher Paolini");
INSERT INTO subgenres (name) VALUES ("adventure");
INSERT INTO subgenres (name) VALUES ("sci-fi");

INSERT INTO character_books (book_id,character_id) VALUES (4,1);
INSERT INTO character_books (book_id,character_id) VALUES (4,2);
INSERT INTO character_books (book_id,character_id) VALUES (5,3);
INSERT INTO character_books (book_id,character_id) VALUES (6,6);
INSERT INTO character_books (book_id,character_id) VALUES (1,5);
INSERT INTO character_books (book_id,character_id) VALUES (2,6);
INSERT INTO character_books (book_id,character_id) VALUES (2,8);
INSERT INTO character_books (book_id,character_id) VALUES (3,7);
INSERT INTO character_books (book_id,character_id) VALUES (5,1);
INSERT INTO character_books (book_id,character_id) VALUES (6,1);
INSERT INTO character_books (book_id,character_id) VALUES (5,2);
INSERT INTO character_books (book_id,character_id) VALUES (5,3);
INSERT INTO character_books (book_id,character_id) VALUES (6,4);
INSERT INTO character_books (book_id,character_id) VALUES (5,4);
INSERT INTO character_books (book_id,character_id) VALUES (2,5);
INSERT INTO character_books (book_id,character_id) VALUES (2,7);
